VERSION 0.8
FROM alpine:3.17.2
RUN apk add --no-cache jq
WORKDIR /quotes

artifact:
  COPY quotes.json ./
  RUN cat ./quotes.json | jq -r ".quotes | .[].quote" > quotes.txt
  RUN echo Generated quotes:
  RUN cat quotes.txt
  SAVE ARTIFACT quotes.txt
