version: "3"
services:
  react:
    image: earthly-demo-react:latest
    ports:
      - 3001:80
  rust:
    image: earthly-demo-rust:latest
    ports:
      - 8000:80
  go:
    image: earthly-demo-go:latest
    ports:
      - 8001:80
  python:
    image: earthly-demo-python:latest
    ports:
      - 8002:80
  node:
    image: earthly-demo-node:latest
    ports:
      - 8003:80
