name: GH-Actions-Satellites-Demo

on:
  push:
    branches:
      - "gha-demo"
  pull_request:
    branches:
      - "gha-demo"
jobs:
  gha-satellites-build:
    runs-on: [earthly-satellite#vlad-gha-demo-sh-foo]
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
      - name: Run CI pipeline
        run: "earthly --ci ./node_server+docker"
